apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-pod   # Selector to target the Pod
  ports:
    - protocol: TCP
      port: 80     # Port on the service
      targetPort: 80  # Port on the Pod
  type: LoadBalancer
