apiVersion: v1
kind: Service
metadata:
  name: myapp-service-mydeploy
spec:
  selector:
    app: mydeploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      # Optionally, specify nodePort if needed
      # nodePort: 30000
  type: LoadBalancer
